Repository wecode-bootcamp-korea/46-2nd-B1A4-frontend, pull requests merged in 2023-06, with the labels that each got.

#2 [46기 김민지] Footer UI 구현
  src/components/Footer/Footer.js
  src/components/Footer/FooterData.js
  src/components/Footer/ShowEffect.js
  src/components/Footer/StyleFooter.js
  src/components/Footer/StyleFooterData.js
  src/components/Modal/FooterDataModal.js
  src/components/Modal/StyleFooterDataModal.js
  src/components/uiData/footerConstData.js
Labels: 멘토 리뷰 요청

#1 [46기 김민지] Filter UI 구현
  package-lock.json
  package.json
  public/data/filterData.json
  src/components/CheckBox/CheckBox.js
  src/components/CheckBox/StyleCheckBox.js
  src/components/Filter/Filter.js
  src/components/Filter/StyleFilter.js
  src/components/Modal/FilterModal.js
  src/components/Modal/FilterShowEffect.js
  src/components/Modal/StyleFilterModal.js
  src/components/RangeSlider/RangeSlider.js
  src/components/RangeSlider/StyleRangeSlider.js
  src/uiData/roomData.js
Labels: 완료

#3 [46기 이재웅] Main UI 구현
  package-lock.json
  package.json
  public/data/main.json
  public/images/room.jpg
  public/images/room10.jpg
  public/images/room11.jpg
  public/images/room2.jpg
  public/images/room3.jpg
  public/images/room4.jpg
  public/images/room5.jpg
  public/images/room6.jpg
  public/images/room7.jpg
  public/images/room8.jpg
  public/images/room9.jpg
  src/components/StudioCard/StudioCard.js
  src/components/StudioCard/StyleStudioCard.js
  src/pages/Main/Main.js
  src/pages/Main/StyleMain.js
Labels: 멘토 리뷰 요청, 수정 완료

#4 [46기 손자현] ADD: Nav Bar & Modal Layout
  package-lock.json
  package.json
  src/components/Login/Login.js
  src/components/Login/StyleLogin.js
  src/components/Modal/Modal.js
  src/components/Modal/StyleModal.js
  src/components/Nav/Nav.js
  src/components/Nav/StyleNav.js
  src/styles/theme.js
Labels: 완료

#9 [46기 이재웅] Mypage UI 구성 완료
  src/Router.js
  src/pages/MyPgae/MyPage.js
  src/pages/MyPgae/StyleMyPage.js
Labels: 멘토 리뷰 요청

#6 [46기 이재웅]Detail 페이지 UI 구성
  package-lock.json
  package.json
  public/data/detailData.json
  public/images/door.png
  public/images/free-icon-parking-6898041.png
  public/images/parking.png
  public/images/wifi.png
  public/index.html
  src/components/Nav/StyleNav.js
  src/pages/Detail/Detail.js
  src/pages/Detail/StyleDetail.js
  src/pages/Detail/component/DayPicker.js
  src/pages/Detail/component/Map.js
  src/pages/Detail/component/StyleDayPicker.js
  src/pages/Detail/component/TimePicker.js
Labels: 멘토 리뷰 요청, 수정 완료

#5 [46기 손자현] ADD: Login Modal Layout, 소셜로그인 기능 구현
  package-lock.json
  package.json
  public/images/logo_v2.png
  public/index.html
  src/Router.js
  src/components/Login/KakaoLogin.js
  src/components/Login/Login.js
  src/components/Login/NaverLogin.js
  src/components/Login/StyleKakaoLogin.js
  src/components/Login/StyleLogin.js
  src/components/Modal/Modal.js
  src/components/Modal/StyleModal.js
  src/components/Nav/Nav.js
  src/components/Nav/NavDropDown.js
  src/components/Nav/NavSearchBox.js
  src/components/Nav/StyleNav.js
  src/components/Nav/StyleNavDropDown.js
  src/components/Nav/StyleNavSearchBox.js
  src/components/StudioCard/StyleStudioCard.js
  src/index.js
  src/pages/Detail/Detail.js
  src/pages/Loading/Loading.js
  src/pages/Loading/Spinner.js
  src/pages/Loading/StyleLoading.js
  src/pages/Main/StyleMain.js
  src/recoilState.js
  src/styles/theme.js
Labels: 멘토 리뷰 요청, 수정 완료

#10 [46기 이재웅] detail 페이지 기능
  package-lock.json
  package.json
  public/data/detailData.json
  src/Router.js
  src/components/Review/Review.js
  src/components/Review/StyleMoreReview.js
  src/components/Review/StyleReview.js
  src/components/StudioCard/StudioCard.js
  src/pages/Detail/Detail.js
  src/pages/Detail/component/DayPicker.js
Labels: 멘토 리뷰 요청, 수정 완료

#11 [46기 이재웅] main 페이지 기능
  package-lock.json
  package.json
  public/data/main.json
  public/images/blankheart.png
  public/images/fillheart.png
  src/components/StudioCard/StudioCard.js
  src/components/StudioCard/StyleStudioCard.js
  src/pages/Main/Main.js
  src/pages/Main/StyleMain.js
Labels: 멘토 리뷰 요청

#12 [46기 손자현] 로컬 네브바 레이아웃
  package-lock.json
  src/components/CheckBox/StyleCheckBox.js
  src/components/Filter/StyleFilter.js
  src/components/Modal/StyleModal.js
  src/components/Nav/LocalNav.js
  src/components/Nav/Nav.js
  src/components/Nav/StyleLocalNav.js
  src/components/Nav/StyleNav.js
  src/pages/Main/Main.js
  src/pages/Main/StyleMain.js
Labels: 멘토 리뷰 요청, 수정 완료

#13 [46기 이재웅] Wishlist 페이지 UI 구성
  public/data/detailData.json
  public/data/wishlistData.json
  src/Router.js
  src/pages/Detail/StyleDetail.js
  src/pages/Main/Main.js
  src/pages/MyPgae/StyleMyPage.js
  src/pages/Wishlist/StyleWishlist.js
  src/pages/Wishlist/Wishlist.js
Labels: 멘토 리뷰 요청, 수정 완료

#16 [46기 김민지] 예약/결제UI 구현 및 토스 API 호출
  package-lock.json
  package.json
  public/images/logo_v1.png
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/StyleFooter.js
  src/components/Modal/OrderRevModal.js
  src/components/Modal/StyleOrderRevModal.js
  src/components/Toss/Fail.js
  src/components/Toss/ReqSuccess.js
  src/components/Toss/ResSuccess.js
  src/components/Toss/StyleResSuccess.js
  src/pages/Main/Main.js
  src/pages/Order/Order.js
  src/pages/Order/RevUpdate.js
  src/pages/Order/StyleOrder.js
  src/pages/Order/StyleRevUpdate.js
  src/pages/Order/StyleTossOrder.js
  src/uiData/orderData.js
Labels: 완료

#15 [46기 손자현] 메인페이지 지도뷰 레이아웃과 기능 구현
  package-lock.json
  package.json
  public/index.html
  src/pages/Main/Main.js
  src/pages/Main/MainMap.js
  src/pages/Main/StyleMainMap.js
Labels: Conflict 해결 요청, 멘토 리뷰 요청

#17 [46기 손자현] 네브 레이아웃 수정 & Logout 기능 구현
  src/Router.js
  src/components/Modal/StyleModal.js
  src/components/MyPage/MyPage.js
  src/components/MyPage/StyleMyPage.js
  src/components/Nav/LocalNav.js
  src/components/Nav/Nav.js
  src/components/Nav/NavDropDown.js
  src/components/Nav/NavSearchBox.js
  src/components/Nav/StyleLocalNav.js
  src/components/Nav/StyleNav.js
  src/components/Nav/StyleNavDropDown.js
  src/pages/Detail/Detail.js
  src/pages/Detail/StyleDetail.js
  src/pages/Loading/Loading-logout.js
  src/pages/Loading/Loading.js
  src/pages/Main/StyleMain.js
  src/pages/MyPgae/MyPage.js
  src/pages/MyPgae/StyleMyPage.js
  src/recoilState.js
Labels: 멘토 리뷰 요청

#20 [46기 이재웅]recoilState 수정 및 공유하기 버튼
  package-lock.json
  src/components/Modal/EmailModal.js
  src/components/Modal/ShareModal.js
  src/components/Modal/StyleShareModal.js
  src/components/Nav/Nav.js
  src/components/Nav/StyleNav.js
  src/components/StudioCard/StudioCard.js
  src/pages/Detail/Detail.js
  src/pages/Detail/StyleDetail.js
  src/pages/Main/Main.js
  src/pages/Order/RevUpdate.js
  src/recoilState.js
Labels: 완료

#19 [46기 이재웅] 카테고리 필터링 기능 추가
  src/components/Nav/LocalNav.js
  src/components/Nav/Nav.js
  src/components/Nav/StyleNav.js
  src/components/StudioCard/StudioCard.js
  src/components/StudioCard/StyleStudioCard.js
  src/pages/Detail/Detail.js
  src/pages/Main/Main.js
Labels: 멘토 리뷰 요청, 수정 완료

#18 [46기 김민지] 예약/결제 기능 구현
  package-lock.json
  package.json
  public/images/kakaoPay.png
  public/images/naverPay.png
  public/images/tossPay.jpg
  src/Router.js
  src/components/Filter/Filter.js
  src/components/Filter/StyleFilter.js
  src/components/Footer/Footer.js
  src/components/Footer/StyleFooter.js
  src/components/Modal/OrderRevModal.js
  src/components/Modal/StyleFilterModal.js
  src/components/Modal/StyleOrderRevModal.js
  src/components/Nav/LocalNav.js
  src/components/Toss/ReqSuccess.js
  src/components/Toss/ResSuccess.js
  src/pages/Main/Main.js
  src/pages/Main/StyleMainMap.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/StyleMyPage.js
  src/pages/Order/Order.js
  src/pages/Order/RevUpdate.js
  src/pages/Order/StyleOrder.js
  src/pages/Order/StyleRevUpdate.js
  src/uiData/orderData.js
Labels: 멘토 리뷰 요청

#21 [46기 이재웅] 디테일 페이지 기능 수정
  src/pages/Detail/Detail.js
  src/pages/Detail/StyleDetail.js
  src/pages/Detail/component/DayPicker.js
  src/pages/Detail/component/StyleDayPicker.js
Labels: 멘토 리뷰 요청

#22 [46기 이재웅] 공유기능 추가
  src/components/Modal/EmailModal.js
  src/components/Modal/ShareModal.js
  src/components/Modal/StyleShareModal.js
Labels: 멘토 리뷰 요청

#24 [46기 김민지] 404페이지 구현
  public/data/filterData.json
  public/images/notFound.png
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Modal/StyleOrderRevModal.js
  src/components/Nav/LocalNav.js
  src/components/NotFound/NotFound.js
  src/components/NotFound/StyleNotFound.js
  src/pages/Detail/Detail.js
  src/pages/Main/Main.js
  src/pages/NotFound/NotFound.js
  src/pages/NotFound/StyleNotFound.js
  src/pages/Order/Order.js
  src/pages/Order/RevUpdate.js
  src/pages/Order/StyleOrder.js
  src/pages/Order/StyleRevUpdate.js
  src/uiData/notFoundData.js
  src/uiData/orderData.js
Labels: 멘토 리뷰 요청

#25 [46기 김민지] favicon 설정 및 수정사항 반영
  package-lock.json
  package.json
  public/favicon.ico
  public/favicon.png
  public/index.html
  src/components/Footer/StyleFooter.js
  src/components/Review/Review.js
  src/pages/NotFound/StyleNotFound.js
Labels: 멘토 리뷰 요청

#23 [46기 손자현] ADD: host 공간 등록페이지 구현
  package-lock.json
  package.json
  public/index.html
  src/Router.js
  src/components/Login/KakaoLogin.js
  src/components/Modal/EmailModal.js
  src/components/Nav/LocalNav.js
  src/components/Nav/Nav.js
  src/components/NotFound/NotFound.js
  src/components/NotFound/StyleNotFound.js
  src/components/Review/Review.js
  src/components/StudioCard/StudioCard.js
  src/components/Toss/ResSuccess.js
  src/pages/Detail/Detail.js
  src/pages/Host/DragDrop.js
  src/pages/Host/HostSignUp.js
  src/pages/Host/ImageUpload.js
  src/pages/Host/PostCode.js
  src/pages/Host/SpaceUpload.js
  src/pages/Host/StyleDragDrop.js
  src/pages/Host/StyleHostSignUp.js
  src/pages/Host/StyleImageUpload.js
  src/pages/Host/StylePostCode.js
  src/pages/Host/StyleSpaceUpload.js
  src/pages/Loading/Loading-logout.js
  src/pages/Loading/Loading.js
  src/pages/Main/Main.js
  src/pages/Main/StyleMainMap.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/StyleMyPage.js
  src/pages/Order/Order.js
  src/recoilState.js
Labels: 멘토 리뷰 요청, 수정 완료

#26 [46기 이재웅] 좋아요 기능 추가
  src/components/Nav/Nav.js
  src/components/StudioCard/StudioCard.js
  src/components/Toss/ResSuccess.js
  src/pages/Detail/Detail.js
  src/pages/Loading/Loading-logout.js
  src/pages/Loading/Loading.js
  src/pages/Main/Main.js
  src/pages/NotFound/NotFound.js
  src/pages/Order/Order.js
  src/pages/Wishlist/StyleWishlist.js
  src/pages/Wishlist/Wishlist.js
Labels: 멘토 리뷰 요청

#27 [46기 김민지] 전체코드 수정사항 반영
  public/data/filterData.json
  public/images/userImg.png
  src/components/Filter/Filter.js
  src/components/Modal/StyleModal.js
  src/components/Modal/StyleShareModal.js
  src/components/Nav/LocalNav.js
  src/components/Nav/Nav.js
  src/components/Review/MoreReview.js
  src/components/Review/Review.js
  src/components/Review/StyleMoreReview.js
  src/components/Review/StyleReview.js
  src/components/StudioCard/StudioCard.js
  src/components/Toss/ReqSuccess.js
  src/components/Toss/ResSuccess.js
  src/components/Toss/StyleResSuccess.js
  src/pages/Detail/Detail.js
  src/pages/Detail/StyleDetail.js
  src/pages/Host/StyleSpaceUpload.js
  src/pages/Loading/StyleLoading.js
  src/pages/Main/Main.js
  src/pages/Main/MainMap.js
  src/pages/Main/StyleMainMap.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/StyleMyPage.js
  src/pages/NotFound/NotFound.js
  src/pages/NotFound/StyleNotFound.js
  src/pages/Order/Order.js
  src/pages/Order/StyleOrder.js
  src/uiData/notFoundData.js
Labels: 멘토 리뷰 요청
